#!/usr/bin/env ruby

require "#{File.dirname(__FILE__)}/util.rb"
require 'fileutils'

if ARGV.size < 1
  STDERR.puts "usage: #{$0} <email address> [username]"
  exit(1)
end

@pwd = Dir.pwd
if ARGV.size >1 
  @email = ARGV[0]
  @common_name = ARGV[1]
else 
  @email = ARGV[0]
  @common_name,domain=@email.split(/@/)
end

if Dir.exist?("clients/#{@common_name}")
  STDERR.puts "Dir clients/#{@common_name} already exists. Remove it first"
  exit(2)
end

FileUtils.mkdir_p("clients/#{@common_name}")
Dir.chdir("clients/#{@common_name}")

output = ""
IO.popen(@cfssl_client, "w+") do |p|
  p.print <<_EOF
{
  "CN": "#{@common_name}",
  "hosts": [""],
  "key": {
      "algo": "ecdsa",
      "size": 256
  },
  "names": [
      {
          "C":  "#{@country}",
          "O":  "#{@organization}",
          "OU": "#{@email}"
      }
  ]
}
_EOF
  p.close_write
  p.each do |out|
    output += out
  end
end
values = JSON.parse(output)

[["csr", "cert.csr"], ["key", "key.pem"], ["cert", "cert.pem"]].each do |names|
  File.open(names[1], "w") do |file|
    file.print values[names[0]]
  end
end

Dir.chdir(@pwd)

